version: '3.4'

services:
  api_server:
    image: crocoplan-api_server-dev
    build:
      context: ../api-server
      target: dev-stage
    ports:
      - "8000:8000"
    command: >
      bash -x -c 'while ! nc -vz db 3306; do sleep 1; done
      && XDEBUG_MODE=off composer install
      && XDEBUG_MODE=off php bin/console doctrine:database:drop --force
      && XDEBUG_MODE=off php bin/console doctrine:database:create
      && XDEBUG_MODE=off php bin/console doctrine:schema:update --force
      && XDEBUG_MODE=off php bin/console doctrine:fixtures:load --append --no-interaction
      && symfony server:start --no-tls'
    environment:
      HOME: /tmp
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # See https://github.com/docker/for-linux/issues/264
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        idekey=PHPSTORM
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=api-server
      XDEBUG_MODE: develop,coverage,debug,gcstats,profile,trace
    volumes:
      - ../api-server:/api-server
      - ./data/.symfony:/.symfony
      - ./data/.composer:/.composer
    user: ${CURRENT_USER:?"Lancez cette commande 'CURRENT_USER=$(id -u):$(id -g) docker-compose -p crocoplan-dev -f docker/docker-compose-dev.yml up'"}
    networks:
      api_server:
      db:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:5.6 # mysql:5.6.49
    environment:
      - MYSQL_ROOT_PASSWORD=crocoplan
      - MYSQL_DATABASE=crocoplan
      - MYSQL_USER=crocoplan
      - MYSQL_PASSWORD=crocoplan
    ports:
      - "3306:3306"
    networks:
      db:

  client_app:
    image: crocoplan-client_app-dev
    build:
      context: ../client-app
      target: common-stage
    ports:
      - "8080:8080"
    working_dir: /client-app
    command: sh -c "yarn install && quasar dev"
    volumes:
      - ../client-app:/client-app
      - ./data/.config:/.config
      - ./data/.quasar-starter-kits:/.quasar-starter-kits
      - ./data/.yarn:/.yarn
      - ./data/.yarnrc:/.yarnrc
      - ./data/.cache:/.cache
      - ./data/.npm:/.npm
    user: ${CURRENT_USER:?"Lancez cette commande 'CURRENT_USER=$(id -u):$(id -g) docker-compose -f docker/docker-compose-dev.yml up'"}
    networks:
      api_server:

networks:
  api_server:
  db:
